version: '2.3'

services:

  redirect:
    image: ghcr.io/leviscop/simple-redirect:main
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectscheme.scheme=https
      - traefik.http.routers.redirect-secure.entrypoints=websecure
      - traefik.http.routers.redirect-secure.rule=Host(`game-1.swarm.leviscop.net`)
      - traefik.http.routers.redirect-secure.service=redirect
      - traefik.http.routers.redirect-secure.tls=true
      - traefik.http.routers.redirect-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.redirect.entrypoints=web
      - traefik.http.routers.redirect.middlewares=redirect-https
      - traefik.http.routers.redirect.rule=Host(`game-1.swarm.leviscop.net`)
      - traefik.http.services.redirect.loadbalancer.server.port=80
    environment:
      - SERVER_REDIRECT=panel.gfelite.net
      # optionally define path to redirect all requests
      # if not set nginx var $request_uri is used
      #- SERVER_REDIRECT_PATH=/landingpage
      # optionally define schema to redirect all requests
      # if not set but X-Forwarded-Proto is send as request header with value 'https' this will be used.
      # In all other cases nginx var `$scheme` is used
      - SERVER_REDIRECT_SCHEME=https
      # optionally define the http code to use for redirection
      # allowed Codes are: 301, 302, 303, 307, 308, default is 301
      - SERVER_REDIRECT_CODE=301
      # optionally define the http code to redirect POST requests
      # if not set or not in allowed Codes, SERVER_REDIRECT_CODE will be used
      #- SERVER_REDIRECT_POST_CODE=
      # optionally define the http code to redirect PUT, PATCH and DELETE requests
      # if not set or not in allowed Codes, SERVER_REDIRECT_CODE will be used
      #- SERVER_REDIRECT_PUT_PATCH_DELETE_CODE=
      # optionally define the location for the nginx access log
      # if not set /dev/stdout is used
      #- SERVER_ACCESS_LOG=/dev/null
      # optionally define the location for the nginx error log
      # if not set /dev/stderr is used
      #- SERVER_ERROR_LOG=/dev/null
